// const data = {
//   flagpolesForAutomobile: [
//     {
//       id: 'fpa01',
//       categotiesClassList: '',
//       imgSrc: '../../images/products/flagpoles/automobile/flagpole-diplomat-premium.jpg',
//       imgIconSrc: '../../images/products/flagpoles/automobile/icons/flagpole-diplomat-premium.jpg',
//       imgAlt: 'флагшток автомобільний',
//       name: 'Флагшток автомобільний ДИПЛОМАТ',
//       material: 'титан',
//       size: 'ДхШхВ: 25х650х3500',
//       price: '25000',
//     },
//     {
//       id: 'fpa02',
//       categotiesClassList: '',
//       imgSrc: '../../images/products/flagpoles/automobile/flagpole-diplomat-premium.jpg',
//       imgIconSrc: '../../images/products/flagpoles/automobile/icons/flagpole-diplomat-premium.jpg',
//       imgAlt: 'флагшток автомобільний',
//       name: 'Флагшток автомобільний ДИПЛОМАТ',
//       material: 'титан',
//       size: 'ДхШхВ: 25х650х3500',
//       price: '26000',
//     },
//     {
//       id: 'fpa03',
//       categotiesClassList: '',
//       imgSrc: '../../images/products/flagpoles/automobile/flagpole-diplomat-premium.jpg',
//       imgIconSrc: '../../images/products/flagpoles/automobile/icons/flagpole-diplomat-premium.jpg',
//       imgAlt: 'флагшток автомобільний',
//       name: 'Флагшток автомобільний ДИПЛОМАТ',
//       material: 'титан',
//       size: 'ДхШхВ: 25х650х3500',
//       price: '27000',
//     },
//   ],

//   flagpolesForStreet: [
//     {
//       id: 'fps01',
//       categotiesClassList: '',
//       imgSrc: '../../images/products/flagpoles/street/flagpole_street_alum.jpg',
//       imgIconSrc: '../../images/products/flagpoles/street/icons/flagpole_street_alum.jpg',
//       imgAlt: 'флагшток вуличний',
//       name: 'Флагшток для вулиці',
//       material: 'алюміній',
//       size: 'ДхШхВ: 25х650х3500',
//       price: '15000',
//     },
//     {
//       id: 'fps02',
//       categotiesClassList: '',
//       imgSrc: '../../images/products/flagpoles/street/flagpole_street_alum.jpg',
//       imgIconSrc: '../../images/products/flagpoles/street/icons/flagpole_street_alum.jpg',
//       imgAlt: 'флагшток вуличний',
//       name: 'Флагшток для вулиці',
//       material: 'алюміній',
//       size: 'ДхШхВ: 25х650х3500',
//       price: '16000',
//     },
//     {
//       id: 'fps03',
//       categotiesClassList: '',
//       imgSrc: '../../images/products/flagpoles/street/flagpole_street_alum.jpg',
//       imgIconSrc: '../../images/products/flagpoles/street/icons/flagpole_street_alum.jpg',
//       imgAlt: 'флагшток вуличний',
//       name: 'Флагшток для вулиці',
//       material: 'алюміній',
//       size: 'ДхШхВ: 25х650х3500',
//       price: '14000',
//     },
//   ],
// };

// export default data;
